# Generated by Django 4.1.7 on 2023-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.DecimalField(decimal_places=0, max_digits=100)),
                ('user_ID', models.DecimalField(decimal_places=0, max_digits=100)),
                ('purchase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.DecimalField(decimal_places=0, max_digits=100)),
                ('user_ID', models.DecimalField(decimal_places=0, max_digits=100)),
                ('text', models.CharField(blank=True, max_length=1200, null=True)),
                ('stars', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
    ]
