# Generated by Django 4.1.7 on 2023-06-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customer_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstLast',
            new_name='lastName',
        ),
    ]
