# Generated by Django 4.1.7 on 2023-06-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_date_joined_customer_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
    ]
