# Generated by Django 4.1.7 on 2023-06-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_customer_groups_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
