# Generated by Django 4.1.7 on 2023-07-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_customer_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='order_ID',
        ),
        migrations.AddField(
            model_name='purchases',
            name='DeliveryDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='OrderSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='purchaseID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
