# Generated by Django 4.1.7 on 2023-07-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_purchases_id_remove_purchases_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='user_ID',
            field=models.TextField(),
        ),
    ]
