# Generated by Django 4.1.7 on 2023-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_purchases_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='purchaseID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
