# Generated by Django 4.1.7 on 2023-07-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_purchases_purchaseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='stars',
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
